<script setup lang="ts">
import { RouterLink } from 'vue-router'
</script>

<template>
  <div class="poc-index">
    <h1>PoC Demos</h1>
    <p class="poc-subtitle">Proof-of-concept prototypes generated by Popilot</p>
    <div class="poc-list">
      <RouterLink to="/poc/board" class="poc-card">
        <div class="poc-icon">&#128203;</div>
        <div class="poc-info">
          <h2>Task Board</h2>
          <p>Kanban board with drag-and-drop, task CRUD, and assignee filtering</p>
        </div>
        <span class="poc-arrow">&rarr;</span>
      </RouterLink>
    </div>
  </div>
</template>

<style scoped>
.poc-index {
  max-width: 640px;
  margin: 0 auto;
  padding: 60px 24px;
}
h1 {
  font-size: 28px;
  font-weight: 800;
  color: var(--text-primary, #111827);
  margin: 0 0 4px;
}
.poc-subtitle {
  font-size: 14px;
  color: var(--text-muted, #9ca3af);
  margin: 0 0 32px;
}
.poc-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.poc-card {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 20px;
  background: #fff;
  border: 1px solid var(--border, #e5e7eb);
  border-radius: 12px;
  text-decoration: none;
  transition: box-shadow 0.15s, border-color 0.15s;
}
.poc-card:hover {
  border-color: var(--primary, #2563eb);
  box-shadow: 0 2px 12px rgba(37, 99, 235, 0.08);
}
.poc-icon {
  font-size: 32px;
}
.poc-info {
  flex: 1;
}
.poc-info h2 {
  font-size: 16px;
  font-weight: 700;
  color: var(--text-primary, #111827);
  margin: 0 0 4px;
}
.poc-info p {
  font-size: 13px;
  color: var(--text-secondary, #6b7280);
  margin: 0;
}
.poc-arrow {
  font-size: 18px;
  color: var(--text-muted, #9ca3af);
}
</style>
